name = "CG"
uuid = "f06a1b11-22c9-4a40-b97b-0654b6cd0df5"
authors = ["Simon Byrne <simonbyrne@gmail.com>"]
version = "0.0.0"

[deps]
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
